[package]
name = "kafka-rust"
version = "0.1.0"
edition = "2021"

[lib]
# Do some stuff


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
